version: "3"
services:
  rabbitmq:
    image: rabbitmq:latest
    hostname: "rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"

  mongodb:
    image: mongo:latest
    hostname: "mongodb"
    ports:
      - "27017:27017"

  app:
    depends_on:
      - rabbitmq
    image: server
    ports:
      - "8000:8000"
